KB-4012:added API flow for withdraw functionality
sunbird-cb/sunbird-cb-workflow pull request #162
Opened 2024-04-16 08:54 UTC by ravisaurav-tarento

2024-04-16 11:21 UTC, SaipradeepR commented on src/main/java/org/sunbird/workflow/service/Workflowservice.java
rename method name to withdrawProfileChangeRequest as readable format ravi.

2024-04-16 11:21 UTC, SaipradeepR commented on src/main/java/org/sunbird/workflow/service/impl/WorkflowServiceImpl.java
"Withdrawn" &  "Withdrawn By User" can u create constants

2024-04-17 04:40 UTC, karthik-tarento requested changes

2024-04-17 04:40 UTC, karthik-tarento commented on src/main/java/org/sunbird/workflow/controller/WorkFlowController.java
> +	@PostMapping("profile/updaterequest/withdraw")
why do you need a new API ?
the transition API -- should handle all type of state changes... 
UI (learner portal  & admin portals) should call the transition API and provide the action as required -- this should work -- just simply enhance the states...

2024-04-19 09:19 UTC, closed without merging